### ISSUE TITLE
Typo in README.md 

### ISSUE THREAD

**Issue by sudobob** [uhppoted/uhppoted-app-wild-apricot#1]
At [https://github.com/uhppoted/uhppoted-app-wild-apricot/blob/master/README.md#credentialsjson](url)

Documentation states wild apricot account id is stored under `account`, when the code is actually looking for `account-id`

Command fails with ambiguous message:

`Error getting contact list (403 The specified account cannot be accessed with the credentials provided.)`

https://github.com/uhppoted/uhppoted-app-wild-apricot/blob/master/commands/credentials.go#L10

**Comment by twystd** [comment]
Thanks for the heads up! I've:

- corrected the typo in the documentation
- added some validation to the credentials to make identifying this problem simpler

re. ambiguous message. Unfortunately the particular call to Wild Apricot that generates this error can fail for a number of reasons - listing the operation and the error returned from Wild Apricot seems to be the most viable option. Am open to suggestions though.

**Comment by uhppoted** [comment]
Fixed in release v0.6.12
