### ISSUE TITLE
Fix HasGroup lookup logic to resolve using group ID

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted-app-wild-apricot#6]
Ref. https://github.com/uhppoted/uhppoted-app-wild-apricot/issues/4

Member record group names returned by the Wild Apricot API are not necessarily consistent with the actual group names - the member group resolution should rather resolve using the group ID and actual group name.

Also - added detailed member group information to the debugging info.

**Comment by twystd** [comment]
Resolved member group names against the system group using the group ID. Pending release v0.8.8,
