### ISSUE TITLE
Example config for when members are "lapsed" or "overdue"

### ISSUE THREAD

**Issue by bborncr** [uhppoted/uhppoted-app-wild-apricot#7]
How do I configure the system to remove members whose status has changed from "active" to "lapsed", "overdue", or "suspended".

**Comment by bborncr** [comment]
After further investigation it appears that the mechanism used to remove members is to change the member to "suspended".

**Comment by uhppoted** [comment]
Hi,

Hmmm, thought I had written that up but it seems to have slipped through the cracks - will make a note to update the README:

- The system will maintain card records for all members in your Wild Apricot database - to actually remove the cards from the controllers the members have to be removed from Wild Apricot. 
- However, you can revoke all permissions for lapsed, overdue or suspended members with the following rules in your _grules_ file:
```
...
rule StartDate "Sets the start date to the 'registered' field" {
     when
         member.HasRegistered()
     then
         permissions.SetStartDate(member.Registered);
         Retract("StartDate");
} 

rule EndDate "Sets the end date to the 'expires' field" {
     when
         member.HasExpires()
     then
         permissions.SetEndDate(member.Expires);
         Retract("EndDate");
}

rule Active "Revokes all access when not active" {
     when
         !member.IsActive()
     then
         permissions.Revoke("*");
         Retract("Active");
}

rule Suspended "Revokes all access when suspended" {
     when
         member.IsSuspended()
     then
         permissions.Revoke("*");
         Retract("Suspended");
}
...
```
If you have _social members_ who are e.g. allowed access to a club room but not to use equipment then you might want to adjust the above rules and use the _IsActive_ to filter individual door permissions. Something like:
```
rule Beginner "Grants an active beginner member access to locker" {
     when
         member.IsActive() && !member.Is("Social Member") && (member.HasGroup("Beginner")
     then
         permissions.Grant("Club Room");
         permissions.Grant("Locker");
         Retract("Beginner");

```
